### ISSUE TITLE
Never loads....

### ISSUE THREAD

**Issue by rlugojr** [gloomyson/SC_Js#3]
Used your hyperlink and no luck.  Blank window and nothing came up on the developer console.  Downloaded the zip and opened index.htm in FireFox.  What is required to get his to run?

**Comment by amilajack** [comment]
Open the dev logs and check the network status. That will let you know if it's still downloading. A lot of the content cannot be included in this project because of copyright reasons.

**Comment by gloomyson** [comment]
The website load is too heavy for web server to handle now, and this game is not playable because audio and images are deleted from project, cannot upload those stuff to github.
You can contact me in private via email or something else

**Comment by rlugojr** [comment]
I see.  Yeah, I didn't see that part about downloading.  Thought that the link would take me to a playable version.  OK, if I can find that download I will give it another try this weekend.  Thanks in advance, really looking forward to playing this.  I love home made games!!!  We need to see more game projects!
